# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(745, 573)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_server_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_server_button.setObjectName("start_server_button")
        self.verticalLayout.addWidget(self.start_server_button)
        self.open_csv_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open_csv_button.setObjectName("open_csv_button")
        self.verticalLayout.addWidget(self.open_csv_button)
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.data_field = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.data_field.setObjectName("data_field")
        self.verticalLayout.addWidget(self.data_field)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CSVReader"))
        self.start_server_button.setText(_translate("MainWindow", "Start Server"))
        self.open_csv_button.setText(_translate("MainWindow", "Open CSV File"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
